### ISSUE TITLE
Code convetions

### ISSUE THREAD

**Issue by OniWithTheHoodie** [OniWithTheHoodie/i-love-web#6]
### html
- Zo min mogelijk div gebruiken
- Goede semantische objecten gebruiken

### css
Maak de css code DRY. Dus eerst de basiselementen stijlen, waarna je de classes stijlt
Werk mobile-first !!!

Wanneer je meerdere objecten aanroept, er een enter tussen elk object komt

```css
p,
ul,
li,
button {
    font-family: var(--font-sans-serif);
    font-size: 1.1em;
    line-height: 1.5em;
}
```

Wanneer je gebruik maakt van een @media-query gebruikt, de waarde binnen het object zet en niet onderaan het bestand.
Zo moet je het dus niet doen.

```css
 #navbar-toggle input:checked ~ .navbar-menu { 
     right: 0; 
     transform: none; 
 } 
  
  
 @media (min-width: 768px) { 
  
     header { 
         border-bottom: none; 
     } 
```
  
maar zo:

```css
header {
    background-color: var(--primary-color-3);
    border-bottom: var(--border-style-black);
    width: 100%;

  @media (min-width: 768px) {
        border-bottom: none;
}
```

## Naamgeving
- Wanneer je een class aanroept, geeft de volgende naamgeving.
- Maak gebruik van de BEM methode. Hierbij geef je de code de volgende naamgeving:
- - Je doet dus onderwerp + object

```css
.stickman-head
```
### JavaScript
- naamgeving: Maak gebruik van CamelCase

# BEM (Block Element Modifier) 

- block elementen geven we een class met een naam. Als je een naam geeft zorg ervoor dat het een logische naam is. voorbeeld als het een article is geef het class naam van article.

- Elementen die je binnen de block element nest geef je de class naam article__naam.

```html

<article class="article">
  <h2 class="article__header">header</h2>
  <p class="article__text">Lorem ipsum dolor sit amet.</p>
</article>

```

Stel dat je meerdere van de zelfde block elementen hebt met andere stijling van elkaar. 
Doe dan dit voor de block elementen article--regular en article--featured zorgt dat je andere stijling kunt geven voor het hele blok.

article__header--regular en article__header--featured zorgt ervoor dat je specifieke elementen kunt stijlen binnen elke blok element .

```html

<!-- Regular Article -->
<article class="article article--regular">
  <h2 class="article__header article__header--regular">Regular Article Header</h2>
  <p class="article__text article__text--regular">This is a regular article.</p>
</article>

<!-- Featured Article -->
<article class="article article--featured">
  <h2 class="article__header article__header--featured">Featured Article Header</h2>
  <p class="article__text article__text--featured">This is a featured article.</p>
</article>


```
# CSS

```css

/* Base block styles */
.article {
  /* Default article styles */
  padding: 20px;
  border: 1px solid #ddd;
}

/* Modifiers for different article types */
.article--regular {
  background-color: #f5f5f5;
}

.article--featured {
  background-color: #ffebcc;
  border-color: #ffa500;
}

/* Element styles */
.article__header {
  font-size: 24px;
  margin-bottom: 10px;
}

.article__text {
  font-size: 16px;
  color: #333;
}

/* Element modifiers for different article types */
.article__header--regular {
  color: #333;
}

.article__header--featured {
  color: #ff4500;
}

.article__text--regular {
  color: #666;
}

.article__text--featured {
  color: #000;
}


```

# HTML

![Image](https://github.com/user-attachments/assets/785e644a-2708-482d-929e-9db6e595e3c2)

## Indention

![Image](https://github.com/user-attachments/assets/1921e3dc-a6ab-4d37-8580-a62abebefc4d)

## Capitilaization

![Image](https://github.com/user-attachments/assets/50881665-1b74-41c3-87c4-a3b5edaf139d)

## Multimedia Fallback

![Image](https://github.com/user-attachments/assets/9a3fa965-336b-41c9-b2c9-00b1be9d7b8a)

# CSS

## Class Naming

![Image](https://github.com/user-attachments/assets/2fae75ef-58f0-403d-9917-e74381816882)

## Declaration Stops

![Image](https://github.com/user-attachments/assets/c3b3336d-6ded-4d45-9b1f-f6c03efbac34)

## Property Name Stops

![Image](https://github.com/user-attachments/assets/31a31082-20df-49c6-a86f-48347e06738d)

## Declaration Block Separation

![Image](https://github.com/user-attachments/assets/e0b5a6c4-e902-4920-9b4b-0e95c960ba66)

## Selector and Declaration Separation

![Image](https://github.com/user-attachments/assets/aa23c304-e0a8-4577-ad29-a317aa255804)

```css

:root,
html,
body {
	margin: 0;
	padding: 0;
	background-color: var(--color-main-bg);
	line-height: 1.6;
	font-size: 1.2rem;
	font-family: 'Open Sans', sans-serif;
}

```

## Rule seperation

![Image](https://github.com/user-attachments/assets/5acf47b3-6054-4856-9623-a32247d67467)

```css

<style>
  main {
    display: flex;
    justify-content: center; 
    align-items: center;     
    height: 100vh;     
  }

  .card {
    display: flex;
    flex-direction: column;
    align-items: center;
    border: 1px solid var(--color-main-text);
    width: 420px;
    height: 805px;
    border-radius: 1em;
  }

  article {
    line-height: 1.2;
    width: 400px;
  }

```
